<a href="https://colab.research.google.com/github/devyani-nandankar/ml-practical_10/blob/main/devyani_Nandankar_CS23018.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lines = []
while True:
    line = input("Enter text (press enter to stop): ")
    if line == "":
        break
    lines.append(line.upper())

print("\n".join(lines))

Enter text (press enter to stop): dyrf
Enter text (press enter to stop): gdfhg
Enter text (press enter to stop): hf


In [ ]:
A = np.array([[int(input()) for _ in range(3)] for _ in range(5)])
B = np.array([[int(input()) for _ in range(2)] for _ in range(3)])

product = np.dot(A, B)
print("Product Matrix:\n",product)

NameError: name 'np' is not defined

In [ ]:
numbers = [1, 2, 3, 4, 5]
print("Max:", max(numbers))
print("Min:", min(numbers))
print("Sum:",sum(numbers))

Max: 5
Min: 1
Sum: 15


In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Sum:",a+b)

Enter first number: 3
Enter second number: 5
Sum: 8


In [ ]:
f1=open("money.txt","w+")
f2=open("data.txt","w+")
f1.write("WELCOME TO PYTHON PROGGRAMING")
f1.seek(0)
dataread=f1.read()
print(dataread)
f2.write(dataread)
f2.seek(0)
print(f2.read())
f1.close()
f2.close()


WELCOME TO PYTHON PROGGRAMING
WELCOME TO PYTHON PROGGRAMING


In [ ]:
# Write text to money.txt
f1 = open("money.txt", "w")
f1.write("Money makes the world go round.")
f1.close()

# Read from money.txt and write to data.txt
f1 = open("money.txt", "r")
text = f1.read()
f1.close()

f2 = open("data.txt", "w")
f2.write(text)
f2.close()

# Read and print content from data.txt
f2 = open("data.txt", "r")
print("Content of data.txt:")
print(f2.read())
f2.close()


Content of data.txt:
Money makes the world go round.


In [ ]:
# Generate numbers from 0 to 1000
numbers = list(range(0, 1001))

# Separate odd and even numbers
ODD_LIST = []
EVEN_LIST = []

for num in numbers:
    if num % 2 == 0:
        EVEN_LIST.append(num)
    else:
        ODD_LIST.append(num)

# Reverse both lists
ODD_LIST.reverse()
EVEN_LIST.reverse()

# Convert lists to tuples
ODD_TUPLE = tuple(ODD_LIST)
EVEN_TUPLE = tuple(EVEN_LIST)

# Print results
print("Reversed ODD_LIST as tuple:")
print(ODD_TUPLE)

print("\nReversed EVEN_LIST as tuple:")
print(EVEN_TUPLE)



Reversed ODD_LIST as tuple:
(999, 997, 995, 993, 991, 989, 987, 985, 983, 981, 979, 977, 975, 973, 971, 969, 967, 965, 963, 961, 959, 957, 955, 953, 951, 949, 947, 945, 943, 941, 939, 937, 935, 933, 931, 929, 927, 925, 923, 921, 919, 917, 915, 913, 911, 909, 907, 905, 903, 901, 899, 897, 895, 893, 891, 889, 887, 885, 883, 881, 879, 877, 875, 873, 871, 869, 867, 865, 863, 861, 859, 857, 855, 853, 851, 849, 847, 845, 843, 841, 839, 837, 835, 833, 831, 829, 827, 825, 823, 821, 819, 817, 815, 813, 811, 809, 807, 805, 803, 801, 799, 797, 795, 793, 791, 789, 787, 785, 783, 781, 779, 777, 775, 773, 771, 769, 767, 765, 763, 761, 759, 757, 755, 753, 751, 749, 747, 745, 743, 741, 739, 737, 735, 733, 731, 729, 727, 725, 723, 721, 719, 717, 715, 713, 711, 709, 707, 705, 703, 701, 699, 697, 695, 693, 691, 689, 687, 685, 683, 681, 679, 677, 675, 673, 671, 669, 667, 665, 663, 661, 659, 657, 655, 653, 651, 649, 647, 645, 643, 641, 639, 637, 635, 633, 631, 629, 627, 625, 623, 621, 619, 617, 615, 613, 6

In [ ]:
print("Enter your lines (press Enter on a blank line to finish):")
lines = []

while True:
    line = input()
    if line == "":
        break
    lines.append(line.upper())

print("\nCapitalized Lines:")
for line in lines:
    print(line)


Enter your lines (press Enter on a blank line to finish):
practice
make
man 
perfect


Capitalized Lines:
PRACTICE
MAKE
MAN 
PERFECT


In [ ]:
import numpy as np

# Input for 5x3 matrix
print("Enter elements for 5x3 matrix:")
a = []
for i in range(5):
    row = input(f"Row {i+1}: ").split()
    row = [float(x) for x in row]
    a.append(row)

# Input for 3x2 matrix
print("\nEnter elements for 3x2 matrix:")
b = []
for i in range(3):
    row = input(f"Row {i+1}: ").split()
    row = [float(x) for x in row]
    b.append(row)

# Convert to numpy arrays
A = np.array(a)
B = np.array(b)

# Multiply matrices
product = np.dot(A, B)

# Print result
print("\nProduct matrix (5x2):")
print(product)


Enter elements for 5x3 matrix:
Row 1: 4 5 7
Row 2: 2 3 5
Row 3:  8 5 3
Row 4: 6  8 0
Row 5: 2 4 5 

Enter elements for 3x2 matrix:
Row 1: 4 5 
Row 2: 6 3
Row 3: 2 6 

Product matrix (5x2):
[[60. 77.]
 [36. 49.]
 [68. 73.]
 [72. 54.]
 [42. 52.]]


In [ ]:
1//2

0

In [ ]:
def func(a,b):
  return b**a
print(func(b=2,2))

SyntaxError: positional argument follows keyword argument (<ipython-input-19-0e6353071b2d>, line 3)

In [ ]:
z=0
y=10
x=y<z and z>y or y<z and z<y

In [ ]:
my_list=[x * x for x in range(5)]
def fun(1st):
  del 1st[1st[2]]
  return 1st
print(fun(my_list))

SyntaxError: invalid decimal literal (<ipython-input-17-0bf7f763ea25>, line 2)

In [ ]:
x=1
y=2
x,y,z=x,x,y
z,y,z=x,y,z
print(x,y,z)

1 1 2


In [ ]:
a=1
b=0
a=a^b
b=a^b
a=a^b
print(a,b)

0 1


In [ ]:
def fun(x):
  if x%2==0:
    return 1
  else:
    return 2
print(fun(fun(2)))

2


In [ ]:
nums=[1,2,3]
vals=nums
del vals[:]

In [ ]:
x=int(input())
y=int(input())
x=x%y
x=x%x
y=y%x
print(y)

3
2


ZeroDivisionError: integer modulo by zero

In [ ]:
x=input()
y=input()
print(x+y)

3
6
36


In [ ]:
print("a","b","c",sep="sep")

asepbsepc


In [ ]:
x=1//5+1/5
print(x)

0.2


In [ ]:
my_tuple[1]=my_tuple[1]+my_tuple[0]

NameError: name 'my_tuple' is not defined

In [ ]:
x=float(input())
y=float(input())
print(y**(1/x))

2
4
2.0


In [ ]:
dct={'one':'two','three':'one','two':'three'}
v=dct['three']
for k in range(len(dct)):
  v=dct[v]
print(v)

one


In [ ]:
1st =[i for in range(-1,-2)]

SyntaxError: invalid decimal literal (<ipython-input-2-1f909f454a6f>, line 1)

In [ ]:
with open('numbers.txt', 'w') as f:
    f.write("123\n456\n789")
file = open('numbers.txt', 'r')
sum = 0
for line in file:
    for char in line:
        if char.isdigit():
            sum += int(char)
print("Sum of all numbers:", sum)
file.close()

Sum of all numbers: 45


In [ ]:
with open('words.txt', 'w') as f:
    f.write("This is the sample text for the file. the word 'the' is here multiple times.")
with open('words.txt', 'r') as file:
    count = 0
    lines = file.readlines()
    for line in lines:
        for char in line.split():
            if char == "the":
                count += 1
    print("Word 'the' in file:", count)

Word 'the' in file: 3


In [ ]:
with open('numbers.txt', 'w') as f:
    f.write("123\n456\n789")
file = open('numbers.txt', 'r')
sum = 0
for line in file:
    for char in line:
        if char.isdigit():
            sum += int(char)
print("Sum of all numbers:", sum)
file.close()

Sum of all numbers: 45


In [ ]:
with open("names.txt","a") as f:
    f.write("David\n")

In [ ]:
f2=open("data.txt","w+")
f1=open("money.txt","w+")
f1.write("WELCOME TO PYTHON PROGRAM")
f1.seek(0)
dataread=f1.read()
print("Source file content:",dataread)
f2.write(dataread)
f2.seek(0)
print("Destination file content:",f2.read())
f1.close()
f2.close()

Source file content: WELCOME TO PYTHON PROGRAM
Destination file content: WELCOME TO PYTHON PROGRAM


In [ ]:
file = open('names.txt', 'r')
count=0
for line in file:
  for char in line:
    if char.isalpha():
      count+=1
print("Charcaters in file:",count)

file.close()

Charcaters in file: 29


In [ ]:
def readfile():
  with open("names.txt","r") as f:
    data=f.read()
    print(data)

print("File content")
readfile()

File content
devyani
nandankar
bhushan
kalpan



In [ ]:
def writeinfile(name):
  with open("names.txt","a") as f:
    f.write(name+"\n")


for i in range(4):
  i=input("Enter name:")
  writeinfile(i)

Enter name:devyani
Enter name:nandankar
Enter name:bhushan
Enter name:kalpan


In [ ]:
import time
import math

def delayed_sqrt(number, delay_ms):
    time.sleep(delay_ms / 1000)
    print(math.sqrt(number))

print("Square root after specific milliseconds:")
delayed_sqrt(16, 1000)
delayed_sqrt(100, 2000)
delayed_sqrt(25098, 3000)

Square root after specific milliseconds:
4.0
10.0
158.42348310777666


In [ ]:
def sample_function():
    a = 10
    b = 20
    c = 30
print(len(locals()) - len(globals()))  # Output: 3

0


In [ ]:
def outer_function():
    def inner_function():
        return "Hello from inner function"
    return inner_function()
print(outer_function())

Hello from inner function


In [ ]:
code = "print('Hello, World!')"
exec(code)

Hello, World!


In [ ]:
def decor(tag):
    def wrapper(func):
        return lambda: f"<{tag}>{func()}</{tag}>"
    return wrapper
@decor("b")
@decor("i")
@decor("u")
def text():
    return "Hello, World!"
print(text())

<b><i><u>Hello, World!</u></i></b>


In [ ]:
def square_list():
    print([n**2 for n in range(1, 31)])
square_list()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [ ]:
def sort_hyphen_sequence(s):
    return "-".join(sorted(s.split("-")))
print(sort_hyphen_sequence("green-red-yellow-black-white"))

black-green-red-white-yellow


In [ ]:
def is_pangram(s):
    return set("abcdefghijklmnopqrstuvwxyz") <= set(s.lower())
print(is_pangram("The quick brown fox jumps over the lazy dog"))

True


In [ ]:
def is_palindrome(s):
    s = s.replace(" ", "").lower()
    return s == s[::-1]

print(is_palindrome("madam"))       # True
print(is_palindrome("nurses run"))  # True
print(is_palindrome("hello"))       # False

True
True
False


In [ ]:
def is_perfect(n):
    return n > 0 and sum(i for i in range(1, n) if n % i == 0) == n

print(is_perfect(6))   # True
print(is_perfect(28))  # True
print(is_perfect(12))  # False

True
True
False


In [ ]:
def even_numbers(lst):
    return [n for n in lst if n % 2 == 0]
print(even_numbers([1, 2, 3, 4, 5, 6, 7, 8, 9]))

[2, 4, 6, 8]


In [ ]:
def is_prime(n):
    if n < 2:
        return False
    return all(n % i != 0 for i in range(2, int(n ** 0.5) + 1))
print(is_prime(7))  # Example usage

True


In [ ]:
def unique_list(lst):
    return list(set(lst))
print(unique_list([1, 2, 3, 3, 3, 3, 4, 5]))

[1, 2, 3, 4, 5]


In [ ]:
def count_case(s):
    upper = sum(1 for c in s if c.isupper())
    lower = sum(1 for c in s if c.islower())
    print("No. of Upper case characters:", upper)
    print("No. of Lower case Characters:", lower)
count_case('The quick Brow Fox')

No. of Upper case characters: 3
No. of Lower case Characters: 12


In [ ]:
def in_range(number, start, end):
    return start <= number <= end
print(in_range(5, 1, 10))  # Example usage

True


In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)
print(factorial(5))  # Example usage

120


In [ ]:
def reverse_string(s):
    return s[::-1]
print(reverse_string("1234abcd"))

dcba4321


In [ ]:
def multiply_list(numbers):
    result = 1
    for num in numbers:
        result *= num
    return result
print(multiply_list([8, 2, 3, -1, 7]))

-336


In [ ]:
def sum_list(numbers):
    return sum(numbers)
print(sum_list([8, 2, 3, 0, 7]))

20


In [ ]:
def max_of_three(a, b, c):
    return max(a, b, c)
print(max_of_three(10, 25, 15))

25


In [ ]:
{'firstname': 'Alice', 'lastname': 'Smith', 'age': 25}

{'firstname': 'Alice', 'lastname': 'Smith', 'age': 25}

In [ ]:
data = {"first name": "Alice", "last name": "Smith", "age ": 25}
data = {key.replace(" ", ""): value for key, value in data.items()}
print(data)

{'firstname': 'Alice', 'lastname': 'Smith', 'age': 25}


In [ ]:
data = {"fruits": ["banana", "apple", "cherry", "date"]}
data["fruits"].sort()
print(data)

{'fruits': ['apple', 'banana', 'cherry', 'date']}


In [ ]:
data = [1, 2, 3, 4]
nested_dict = current = {}
for item in data:
    current[item] = {}
    current = current[item]
print(nested_dict)

{1: {2: {3: {4: {}}}}}


In [ ]:
data = {'A': [1, 2, 3, 4, 5, 6], 'B': [7, 8]}
for key in data:
    print(len(data[key]))

6
2


In [ ]:
data = {"Name": "Alice", "Age": 25, "City": "New York"}
for key, value in data.items():
    print(key, "|", value)

Name | Alice
Age | 25
City | New York


In [ ]:
from collections import Counter
string = "SBJAIN"
char_count = dict(Counter(string))
print(char_count)

{'S': 1, 'B': 1, 'J': 1, 'A': 1, 'I': 1, 'N': 1}


In [ ]:
from collections import Counter
data = [{'item': 'item1', 'amount': 400},
        {'item': 'item2', 'amount': 300},
        {'item': 'item1', 'amount': 750}]
result = Counter()
for entry in data:
    result[entry['item']] += entry['amount']
print(result)

Counter({'item1': 1150, 'item2': 300})


In [ ]:
data = {"a": 10, "b": 50, "c": 30, "d": 40, "e": 20}
highest_values = sorted(data.values(), reverse=True)[:3]
print("Top 3 values:", highest_values)

Top 3 values: [50, 40, 30]


In [ ]:
from itertools import product
data = {'1': ['a', 'b'], '2': ['c', 'd']}
for combo in product(*data.values()):
    print(''.join(combo))

ac
ad
bc
bd


In [ ]:
data = [{"V": "S001"}, {"V": "S002"}, {"VI": "S001"}, {"VI": "S005"},
        {"VII": "S005"}, {"V": "S009"}, {"VIII": "S007"}]
unique_values = set(value for item in data for value in item.values())
print(unique_values)

{'S009', 'S001', 'S005', 'S002', 'S007'}


In [ ]:
d1 = {'a': 100, 'b': 200, 'c': 300}
d2 = {'a': 300, 'b': 200, 'd': 400}
for key in d2:
    d1[key] = d1.get(key, 0) + d2[key]
print(d1)

{'a': 400, 'b': 400, 'c': 300, 'd': 400}


In [ ]:
data = {}
if not data:
    print("Dictionary is empty")
else:
    print("Dictionary is not empty")

Dictionary is empty


In [ ]:
data = {"a": 1, "b": 2, "c": 2, "d": 3, "e": 1}
unique_dict = dict(set(data.items()))
print(unique_dict)

{'c': 2, 'd': 3, 'b': 2, 'e': 1, 'a': 1}


In [ ]:
class Person:
    def __init__(self, name, age, city):
        self.name = name
        self.age = age
        self.city = city
person = Person("Alice", 25, "New York")
person_dict = person.__dict__
print(person_dict)

{'name': 'Alice', 'age': 25, 'city': 'New York'}


In [ ]:
data = {"a": 10, "b": 5, "c": 20, "d": 15}
max_value = max(data.values())
min_value = min(data.values())
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 20
Minimum value: 5


In [ ]:
data = {"b": 2, "a": 1, "c": 3}
sorted_dict = dict(sorted(data.items()))
print(sorted_dict)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
keys = ["a", "b", "c"]
values = [1, 2, 3]
mapped_dict = dict(zip(keys, values))
print(mapped_dict)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
data = {"a": 1, "b": 2, "c": 3}
key_to_remove = "b"
if key_to_remove in data:
    del data[key_to_remove]
print(data)

{'a': 1, 'c': 3}


In [ ]:
data = {"a": 2, "b": 3, "c": 4}
result = 1
for value in data.values():
    result *= value
print("Product of all values:", result)

Product of all values: 24


In [ ]:
data = {"a": 10, "b": 20, "c": 30}
total = sum(data.values())
print("Sum of all values:", total)

Sum of all values: 60


In [ ]:
data = {"name": "Alice", "age": 25, "city": "New York"}
for key in data:
    print(key, ":", data[key])

name : Alice
age : 25
city : New York


In [ ]:
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}
dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
squares = {x: x*x for x in range(1, 16)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [ ]:
n = int(input("Enter a number: "))
squares = {x: x*x for x in range(1, n+1)}
print(squares)

Enter a number: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
data = {"a": 1, "b": 2, "c": 3}
for key, value in data.items():
    print(key, ":", value)

a : 1
b : 2
c : 3


In [ ]:
sample_dict = {1: 10, 2: 20, 3: 30}
key = 2
print(key in sample_dict)

True


In [ ]:
dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}
new_dict = {**dic1, **dic2, **dic3}
print(new_dict)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [ ]:
sample_dict = {0: 10, 1: 20}  //1
sample_dict[2] = 30
print(sample_dict)

{0: 10, 1: 20, 2: 30}


In [ ]:
def factorial1():
    num = int(input("Enter a number: "))
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    print("Factorial:", fact)

def factorial2(num):
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    print("Factorial:", fact)

def factorial3():
    num = int(input("Enter a number: "))
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    return fact

def factorial4(num):
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    return fact

# Calling all functions
factorial1()
num = int(input("Enter a number: "))
factorial2(num)
print("Factorial:", factorial3())
num = int(input("Enter a number: "))
print("Factorial:", factorial4(num))

Enter a number: 5
Factorial: 120
Enter a number: 6
Factorial: 720
Enter a number: 4
Factorial: 24
Enter a number: 5
Factorial: 120


In [ ]:
def cube1():
    num = int(input("Enter a number: "))
    print("Cube:", num ** 3)

def cube2(num):
    print("Cube:", num ** 3)

def cube3():
    return int(input("Enter a number: ")) ** 3

def cube4(num):
    return num ** 3

# Calling all functions
cube1()
num = int(input("Enter a number: "))
cube2(num)
print("Cube:", cube3())
num = int(input("Enter a number: "))
print("Cube:", cube4(num))

Enter a number: 6
Cube: 216
Enter a number: 5
Cube: 125
Enter a number: 4
Cube: 64
Enter a number: 8
Cube: 512


In [ ]:
string = "python 3.0"
string_tuple = tuple(string)
print(string_tuple)

('p', 'y', 't', 'h', 'o', 'n', ' ', '3', '.', '0')


In [ ]:
data = [(), (), ('',), ('a', 'b'), ('a', 'b', 'c'), ('d',)]
cleaned_data = [t for t in data if t]
print(cleaned_data)

[('',), ('a', 'b'), ('a', 'b', 'c'), ('d',)]


In [ ]:
my_list = [(1, 'a'), (2, 'b'), (3, 'c')]
my_dict = dict(my_list)
print(my_dict)

{1: 'a', 2: 'b', 3: 'c'}


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple[::-1])

(5, 4, 3, 2, 1)


In [ ]:
my_list = [(1, 'a'), (2, 'b'), (3, 'c')]
list1, list2 = zip(*my_list)
print(list(list1))
print(list(list2))

[1, 2, 3]
['a', 'b', 'c']


In [ ]:
my_tuple = (("a", 1), ("b", 2), ("c", 3))
my_dict = dict(my_tuple)
print(my_dict)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
my_tuple = (10, 20, 30, 40, 50)
print(my_tuple.index(30))

2


In [ ]:
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
print(my_tuple[2:6])

(3, 4, 5, 6)


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
new_tuple = tuple(item for item in my_tuple if item != 3)
print(new_tuple)

(1, 2, 4, 5)


In [ ]:
my_list = [1, 2, 3, 4, 5]
my_tuple = tuple(my_list)
print(my_tuple)

(1, 2, 3, 4, 5)


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
print(3 in my_tuple)

True


In [ ]:
my_tuple = (1, 2, 3, 2, 4, 5, 3, 6, 2)
print(set([item for item in my_tuple if my_tuple.count(item) > 1]))

{2, 3}


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
clone_tuple = my_tuple[:]
print(clone_tuple)

(1, 2, 3, 4, 5)


In [ ]:
my_tuple = (10, 20, 30, 40, 50, 60, 70)
print(my_tuple[-4])

40


In [ ]:
my_tuple = ('H', 'e', 'l', 'l', 'o')
string = ""
for char in my_tuple:
    string += char
print(string)

Hello


In [ ]:
my_tuple = (1, 2, 3)
new_tuple = my_tuple + (4,)
print(new_tuple)

(1, 2, 3, 4)


In [ ]:
my_tuple = (10, 20, 30)
a, b, c = my_tuple
print(a)
print(b)
print(c)

10
20
30


In [ ]:
numbers_tuple = (10, 20, 30, 40, 50)
print(numbers_tuple[2])

30


In [ ]:
my_tuple = (42, "hello", 3.14, True, [1, 2, 3])
print(my_tuple)

(42, 'hello', 3.14, True, [1, 2, 3])


In [ ]:
my_tuple = (1, 2, 3, "hello", 3.14)
print(my_tuple)

(1, 2, 3, 'hello', 3.14)


In [ ]:
squares_tuple = tuple(i**2 for i in range(1, 6))
print(squares_tuple)

(1, 4, 9, 16, 25)


In [ ]:
my_tuple = (5, 2, 8, 1, 3)
sorted_tuple = tuple(sorted(my_tuple))
print(sorted_tuple)

(1, 2, 3, 5, 8)


In [ ]:
my_tuple = (1, 2, 3, 4, 3, 5)
print(my_tuple.index(3))

2


In [ ]:
my_tuple = (True, True, False)
print(all(my_tuple))

False


In [ ]:
my_tuple = (1, 2, 3, 2, 4, 2)
print(my_tuple.count(2))

3


In [ ]:
my_tuple = (5, 12, 3, 8, 15)
print(min(my_tuple))
print(max(my_tuple))

3
15


In [ ]:
my_list = [1, 2, 3]
my_tuple = tuple(my_list)
print(my_tuple)

(1, 2, 3)


In [ ]:
my_tuple = (1, 2, 3)
new_tuple = my_tuple * 3
print(new_tuple)

(1, 2, 3, 1, 2, 3, 1, 2, 3)


In [ ]:
my_tuple = (10, 20, 30, 40, 50)
print(len(my_tuple))

5


In [ ]:
my_tuple = (0, 1, 2, 3, 4, 5)
print(my_tuple[2:5])

(2, 3, 4)


In [ ]:
my_tuple = (1, 3, 5, 7, 9)
print(7 in my_tuple)

True


In [ ]:
a, b, c = ("a", "b", "c")
print(a)
print(b)
print(c)

a
b
c


In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
new_tuple = tuple1 + tuple2
print(new_tuple)

(1, 2, 3, 4, 5, 6)


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple[2])

3


In [ ]:
my_tuple = (10, "hello", 3.14)//1

In [ ]:
l = [10, 22, 30, 44, 55, 66, 77]
for num in l:
    if num % 5 == 0:
        print(num)

10
30
55


In [ ]:
num = [2, 3, 4, 5, 2, 6, 3, 2]
result = list(set(num))
print("Result:", result)

Result: [2, 3, 4, 5, 6]


In [ ]:
numbers = [2, 23, 24, 51, 46, 67]
even = []
odd = []
for num in numbers:
    (even if num % 2 == 0 else odd).append(num)
print("Even:", even)
print("Odd:", odd)

Even numbers: [2, 24, 46]
Odd numbers: [23, 51, 67]


In [ ]:
list1 = [10, 20, [300, 400, [5000, 6000], 500, 30, 40]]
list1[2][2].append(7000)
print(list1)

[10, 20, [300, 400, [5000, 6000, 7000], 500, 30, 40]]


In [ ]:
colors = ["Red", "Blue", "Green"]
numbers = [1, 2, 3]
combined = []
combined.extend(colors)
combined.extend(numbers)
print("Combined list:", combined)
combined.clear()
print("Empty combined list:", combined)

Combined list: ['Red', 'Blue', 'Green', 1, 2, 3]
Empty combined list: []


In [ ]:
historical_places = ["Ayodhya", "Mathura", "Kashi", "Hampi", "Somnath"]
my_places = historical_places.copy()
my_places.append("Ajanta Caves")
historical_places = historical_places[2:]
print("Historical Places:", historical_places)
print("My Places:", my_places)

Historical Places: ['Kashi', 'Hampi', 'Somnath']
My Places: ['Ayodhya', 'Mathura', 'Kashi', 'Hampi', 'Somnath', 'Ajanta Caves']


In [ ]:
sweets = ["Gulab Jamun", "Jalebi", "Rasgulla", "Barfi", "Laddu", "Gulab Jamun"]
print("Gulab Jamun count:", sweets.count("Gulab Jamun"))
removed_sweet = sweets.pop()
print("Removed sweet:", removed_sweet)
print("Updated sweets list:", sweets)

Gulab Jamun count: 2
Removed sweet: Gulab Jamun
Updated sweets list: ['Gulab Jamun', 'Jalebi', 'Rasgulla', 'Barfi', 'Laddu']


In [ ]:
books = ["Veer Savarkar", "The Rise of the India", "Shivaji Maharaj"]
books.extend(["Gitanjali", "Bhakti Saints"])
books.sort()
books.reverse()
print("Number of books:", len(books))
print(books)

Number of books: 5
['Veer Savarkar', 'The Rise of the India', 'Shivaji Maharaj', 'Gitanjali', 'Bhakti Saints']


In [ ]:
spices = ["Turmeric", "Cumin", "Coriander"]
spices.append("Cardamom")
spices.insert(0, "Ginger")
spices.remove("Cumin")

if "Cloves" not in spices:
    print("Need to buy Cloves")

print(spices)

Need to buy Cloves
['Ginger', 'Turmeric', 'Coriander', 'Cardamom']


In [ ]:
languages = ["Python", "Java"]
languages.append("C++")
languages[1] = "JavaScript"
languages.pop(0)
print(languages)

['JavaScript', 'C++']


In [ ]:
festivals = ["Navratri", "Eid", "Ganesh Chaturthi", "Pongal"]
festivals.insert(1, "Holi")
festivals.append("Diwali")
festivals.pop(0)
print(festivals)

['Holi', 'Eid', 'Ganesh Chaturthi', 'Pongal', 'Diwali']


In [ ]:
bollywood_movies = ["Sholay", "Zindagi Na Milegi Dobara", "Kabir Singh", "3 Idiots"]
bollywood_movies.insert(0, "DDLG")
bollywood_movies.pop(2)
bollywood_movies[-1] = "Uri"
print(bollywood_movies)

['DDLG', 'Sholay', 'Kabir Singh', 'Uri']


In [ ]:
favorite_foods = ["Pizza", "Pasta", "Sushi", "Burger", "Ice Cream"]
favorite_foods.append("Biryani")
favorite_foods.remove("Pizza")
favorite_foods[1] = "Dosa"
print(favorite_foods)

['Pasta', 'Dosa', 'Burger', 'Ice Cream', 'Biryani']


In [ ]:
travel_destinations = ["Delhi", "Ayodha", "Kashi", "Mathura"]
travel_destinations[0] = "Somnath"
travel_destinations.append("Somnath")
print(travel_destinations)

['Somnath', 'Ayodha', 'Kashi', 'Mathura', 'Somnath']


In [ ]:
movies = ["Jawan", "Pathaan", "Gadar 2", "Animal", "Dunki"]

print("Movie at index 1:", movies[1])
print("Second last movie:", movies[-2])

Movie at index 1: Pathaan
Second last movie: Animal


In [ ]:

groceries = ["Milk", "Eggs", "Bread", "Apples", "Rice"]

print("First 3 items:", groceries[:3])
print("Last 2 items:", groceries[-2:])

First 3 items: ['Milk', 'Eggs', 'Bread']
Last 2 items: ['Apples', 'Rice']


In [ ]:
#Devyani Nandankar(CS23018)
monuments = ["Ayodhya Ram Janmabhoomi", "Sharada Peeth", "Tirupati Balaji", "Somnath Temple"]

print("Monument at index 2:", monuments[2])
print("Monument at index 0:", monuments[0])
print("Last monument:", monuments[-1])

Monument at index 2: Tirupati Balaji
Monument at index 0: Ayodhya Ram Janmabhoomi
Last monument: Somnath Temple


In [ ]:
#Devyani Nandankar(CS23018)
rainbow = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"]

print("First color:", rainbow[0])
print("Last color:", rainbow[-1])
print("Green color:", rainbow[3])

First color: red
Last color: violet
Green color: green


In [ ]:
#Devyani Nandankar(CS23018)
cricket_team = ["Virat", "Rohit", "Jasprit", "Hardik", "Ravindra"]

print("Captain:", cricket_team[1])
print("Last player:", cricket_team[-1])
print("Third player:", cricket_team[2])

Captain: Rohit
Last player: Ravindra
Third player: Jasprit


In [ ]:
#Devyani Nandankar(CS23018)
paragraph = input("Enter the paragraph: ")
old_string = input("Enter the string to replace: ")
new_string = input("Enter the new string: ")
updated_paragraph = paragraph.replace(old_string, new_string)
print("\nUpdated Paragraph:\n", updated_paragraph)

Enter the paragraph: devyani nandankar is a good girl
Enter the string to replace: is
Enter the new string: has

Updated Paragraph:
 devyani nandankar has a good girl


In [ ]:
#Devyani Nandankar(CS23018)
chars = input("Enter characters separated by space: ").split()
string = ""
for char in chars:
    string += char
print("String:", string)

Enter characters separated by space: H E L L O
String: HELLO


In [ ]:
#Devyani Nandankar(CS23018)
string = input("Enter a string: ")
letter_count = 0
digit_count = 0
for char in string:
    if char.isalpha():
        letter_count += 1
    elif char.isdigit():
        digit_count += 1

print(f"Total letters: {letter_count}")
print(f"Total digits: {digit_count}")

Enter a string: sbjain college123
Total letters: 13
Total digits: 3


In [ ]:
#Devyani Nandankar(CS23018)
s = input("Enter a string: ")

upper_count = sum(1 for char in s if char.isupper())
lower_count = sum(1 for char in s if char.islower())

print("Uppercase letters:", upper_count)
print("Lowercase letters:", lower_count)

Enter a string: Devyani Nandankar
Uppercase letters: 2
Lowercase letters: 14


In [ ]:
#Devyani Nandankar(CS23018)
string = input("Enter a string: ")
char_count = {}
for char in string:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1
max_char = None
max_count = 0
for char in char_count:
    if char_count[char] > max_count:
        max_count = char_count[char]
        max_char = char
print(f"Character with maximum frequency: '{max_char}' ({max_count} times)")

Enter a string: devyani nandankar
Character with maximum frequency: 'a' (4 times)


In [ ]:
#Devyani Nandankar(CS23018)
input_string = input("Enter a string: ")
digit_count = sum(c.isdigit() for c in input_string)
alpha_count = sum(c.isalpha() for c in input_string)
other_count = len(input_string) - (digit_count + alpha_count)
print("Number of digits:", digit_count)
print("Number of alphabets:", alpha_count)
print("Number of other characters:", other_count)

Enter a string: 132devyani@
Number of digits: 3
Number of alphabets: 7
Number of other characters: 1


In [ ]:
#Devyani Nandankar(CS23018)
string = input("Enter a string: ")

half_length = len(string) // 2
first_half = string[:half_length].upper()
second_half = string[half_length:].lower()

result = first_half + second_half

print("Modified string:", result)


Enter a string: devyani nandankar
Modified string: DEVYANI nandankar


In [ ]:
#Devyani Nandankar(CS23018)
sentence = input("Enter a sentence: ")
words = sentence.split()

print("Even length words:")
for word in words:
    if len(word) % 2 == 0:
        print(word)


Enter a sentence: even
Even length words:
even


In [ ]:
#Devyani Nandankar(CS23018)
string = input("Enter a string: ")

length_for = sum(1 for _ in string)

length_while = 0
temp_string = string
while temp_string:
    temp_string = temp_string[1:]
    length_while += 1

length_join_count = (" ".join(string)).count(" ") + 1 if string else 0

print("Length (for loop):", length_for)
print("Length (while loop):", length_while)
print("Length (join and count):", length_join_count)

Enter a string: devyani
Length (for loop): 7
Length (while loop): 7
Length (join and count): 7


In [ ]:
#Devyani Nandankar(CS23018)
string = input("Enter a string: ")
i = int(input("Enter the index to remove: "))

result_split = string[:i] + string[i+1:] if i < len(string) else string
result_replace = string.replace(string[i], '', 1) if i < len(string) else string
result_slicing = string[:i] + string[i+1:] if i < len(string) else string
result_join = ''.join([string[j] for j in range(len(string)) if j != i]) if i < len(string) else string

print("Original string:", string)
print("After removing character at index", i, "(split method):", result_split)
print("After removing character at index", i, "(replace method):", result_replace)
print("After removing character at index", i, "(slicing method):", result_slicing)
print("After removing character at index", i, "(join method):", result_join)

Enter a string: nandankar
Enter the index to remove: 4
Original string: nandankar
After removing character at index 4 (split method): nandnkar
After removing character at index 4 (replace method): nndankar
After removing character at index 4 (slicing method): nandnkar
After removing character at index 4 (join method): nandnkar


In [ ]:
#Devyani Nandankar(CS23018)
s = input("Enter a string: ")
if s == s[::-1]:
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")
mid = len(s)
if s[:mid] == s[-mid:]:
    print("The string is symmetrical.")
else:
    print("The string is not symmetrical.")


Enter a string: mom
The string is a palindrome.
The string is symmetrical.


In [ ]:
#Devyani Nandankar(CS23018)
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])
result = np.setdiff1d(array1, array2)
print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:")
print(result)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays:
[ 0 20 60 80]


In [ ]:
#Devyani Nandankar(CS23018)
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6])
print("Original array")
print(arr)
print("Power raised Array")
print(np.power(arr, arr))

Original array
[0 1 2 3 4 5 6]
Power raised Array
[    1     1     4    27   256  3125 46656]


In [ ]:
#Devyani Nandankar(CS23018)
import numpy as np
list=[]
for i in range(2,11):
    value=i
    list.append(value)
arr=np.array(list)
matrix = np.array(arr).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#Devyani Nandankar(CS23018)
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
matrix = np.array(arr).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Devyani Nandankar(CS23018)
import numpy as np
N=int(input("Enter the number of rows:"))
M=int(input("Enter the number of columns:"))
list1=[]
for i in range(N):
  list=[]
  for j in range(M):
    value=int(input())
    list.append(value)
  list1.append(list)
Array1=np.array(list1)
print("Array is:")
print(Array1)
print("Transpose Array is:")
print(Array1.T)
print("Flattened Array is:")
print(Array1.flatten())

Enter the number of rows:2
Enter the number of columns:2
3
4
4
5
Array is:
[[3 4]
 [4 5]]
Transpose Array is:
[[3 4]
 [4 5]]
Flattened Array is:
[3 4 4 5]


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")

  print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1,6):
  for j in range(1,i+1):
    print(i,end=" ")
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(0,5):
  for j in range(i,-1,-1):
    print(j+1,end=" ")
  print()

1 
2 1 
3 2 1 
4 3 2 1 
5 4 3 2 1 


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1,6):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
#Devyani Nandankar(CS23018)
n = int(input("enter the number of rows:"))
num=1
for i in range(1,n+1):
   for j in range(1,i+1):
    print(i*2,end=" ")
    i=i+1
   print()

enter the number of rows:5
2 
4 6 
6 8 10 
8 10 12 14 
10 12 14 16 18 


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1, 6):
    for j in range(1, i + 1):
        if j % 2 != 0:
            print("1", end="")
        else:
            print("0", end="")
    print()

1
10
101
1010
10101


Task 2

In [ ]:
#Devyani Nandankar(CS23018)
for i in range(6):
  letter=65
  for j in range(1,i+1):
    print(chr(letter),end='')
    letter+=1
  print()


A
AB
ABC
ABCD
ABCDE


In [ ]:
#Devyani Nandankar(CS23018)
str1 = ['p', 'y', 't', 'o', 'n']
length = len(str1)

for i in range(length):
    for j in range(i + 1):
        print(str1[j], end=" ")
    print()

p 
p y 
p y t 
p y t o 
p y t o n 


In [ ]:
#Devyani Nandankar(CS23018)
str1 = ['p', 'y', 't', 'o', 'n']
length = len(str1)

for i in range(length):
    for j in range(i + 1):
        print(str1[i], end=" ")
    print()

p 
y y 
t t t 
o o o o 
n n n n n 


In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1, 6):
    for j in range(1, i + 1):
        if j % 2 != 0:
            print("*", end="")
        else:
            print("#", end="")
    print()

*
*#
*#*
*#*#
*#*#*


Task 3


In [ ]:
#Devyani Nandankar(CS23018)
n = int(input("Enter a number:"))
for i in range(1, n + 1):
    print(i, end="")


Enter a number:3
123

Task 4


In [ ]:
 #Devyani Nandankar(CS23018)
 for i in range(1,6):
    for space in range((5-i),0,-1):
      print(" ",end=" ")
    for j in range((2*i-1), 0, -1):
      print("*",end=" ")
    print()


        * 
      * * * 
    * * * * * 
  * * * * * * * 
* * * * * * * * * 


Task 5

In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1,6):
  for space in range(1,i):
    print(" ",end=" ")
  for j in range(10,(2*i-1),-1):
    print("*",end=" ")
  print()

* * * * * * * * * 
  * * * * * * * 
    * * * * * 
      * * * 
        * 


Task 6

In [ ]:
#Devyani Nandankar(CS23018)
for i in range(1,6):
  for j in range(1,i+1):
    print("*",end=" ")
  print()
for i in range(6,0,-1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


Task 7

In [ ]:
start = int(input("Enter the starting number: "))
end = int(input("Enter the ending number: "))

for num in range(start, end + 1):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num, end=" ")


Enter the starting number: 2
Enter the ending number: 50
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 

In [ ]:
#Devyani Nandankar(CS23018)
def calculate_painting_cost():
    interior_cost = 18
    exterior_cost = 12

    num_interior_walls = int(input("Enter the number of Interior walls: "))
    num_exterior_walls = int(input("Enter the number of Exterior walls: "))

    total_cost = 0

    for i in range(num_interior_walls):
        area = float(input(f"Enter the surface area of Interior wall {i+1}: "))
        total_cost += area * interior_cost

    for i in range(num_exterior_walls):
        area = float(input(f"Enter the surface area of Exterior wall {i+1}: "))
        total_cost += area * exterior_cost

    print(f"Total cost of painting: Rs. {total_cost:.2f}")

calculate_painting_cost()


Enter the number of Interior walls: 2
Enter the number of Exterior walls: 3
Enter the surface area of Interior wall 1: 54
Enter the surface area of Interior wall 2: 34
Enter the surface area of Exterior wall 1: 23
Enter the surface area of Exterior wall 2: 34
Enter the surface area of Exterior wall 3: 34
Total cost of painting: Rs. 2676.00


In [ ]:
#Devyani Nandankar(CS23018)
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32


celsius = float(input("Enter the temperature in Celsius: "))


fahrenheit = celsius_to_fahrenheit(celsius)


print(f"Temperature: {celsius}°C = {fahrenheit}°F")


if celsius < -273.15:
    print("The temperature is invalid because it is below absolute zero.")
elif celsius == -273.15:
    print("The temperature is absolute 0.")
elif -273.15 < celsius < 0:
    print("The temperature is below freezing.")
elif celsius == 0:
    print("The temperature is at the freezing point.")
elif 0 < celsius < 100:
    print("The temperature is in the normal range.")
elif celsius == 100:
    print("The temperature is at the boiling point.")
else:
    print("The temperature is above the boiling point.")


Enter the temperature in Celsius: 65
Temperature: 65.0°C = 149.0°F
The temperature is in the normal range.


In [ ]:
#Devyani Nandankar(CS23018)
def is_leap_year(year):

    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False


year = int(input("Enter a year: "))


if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


Enter a year: 2023
2023 is not a leap year.


In [ ]:
#Devyani Nandankar(CS23018)
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))


addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2
if num2 != 0:
    division = num1 / num2
else:
    division = "Error! Division by zero."


print(f"Addition: {num1} + {num2} = {addition}")
print(f"Subtraction: {num1} - {num2} = {subtraction}")
print(f"Multiplication: {num1} * {num2} = {multiplication}")
print(f"Division: {num1} / {num2} = {division}")


Enter first number: 64
Enter second number: 34
Addition: 64.0 + 34.0 = 98.0
Subtraction: 64.0 - 34.0 = 30.0
Multiplication: 64.0 * 34.0 = 2176.0
Division: 64.0 / 34.0 = 1.8823529411764706


In [ ]:
#Devyani Nandankar(CS23018)
def calculate_bonus(percentage, salary):

    if 90 <= percentage <= 100:
        bonus = salary * 0.20
    elif 80 <= percentage < 90:
        bonus = salary * 0.10
    elif 70 <= percentage < 80:
        bonus = salary * 0.05
    else:
        bonus = 0
    return bonus


salary = float(input("Enter the employee's salary: "))
percentage = float(input("Enter the employee's performance percentage: "))
bonus = calculate_bonus(percentage, salary)

if bonus > 0:
    print(f"The employee's bonus is: Rs.{bonus}")
else:
    print("The employee is not eligible for a bonus.")


Enter the employee's salary: 45000
Enter the employee's performance percentage: 87
The employee's bonus is: Rs.4500.0


In [ ]:
#Devyani Nandankar(CS23018)
def check_loan_eligibility(credit_score):
    if credit_score >= 750:
        return "Eligible for all loan types."
    elif 650 <= credit_score < 750:
        return "Eligible for most loan types."
    elif 550 <= credit_score < 650:
        return "Eligible for some loan types with higher interest rates."
    else:
        return "May not be eligible for a loan."

credit_score = int(input("Enter the applicant's credit score: "))

eligibility = check_loan_eligibility(credit_score)

print(eligibility)


Enter the applicant's credit score: 768
Eligible for all loan types.


In [ ]:
#Devyani Nandankar(CS23018)
fever = input("Do you have a fever? (Yes/No): ").strip().lower()
cough = input("Do you have a cough? (Yes/No): ").strip().lower()
sore_throat = input("Do you have a sore throat? (Yes/No): ").strip().lower()

if fever == "yes" and cough == "yes":
    print("Possible Flu or Cold.")
elif fever == "yes" and sore_throat == "yes":
    print("Possible Strep Throat.")
elif cough == "yes" and sore_throat == "yes":
    print("Possible Cold.")
else:
    print("Cannot make a diagnosis based on the symptoms provided.")


Do you have a fever? (Yes/No): yes
Do you have a cough? (Yes/No): no
Do you have a sore throat? (Yes/No): yes
Possible Strep Throat.


In [ ]:
#Devyani Nandankar(CS23018)
INTERIOR_COST = 18
EXTERIOR_COST = 12

num_interior_walls = int(input("Enter number of Interior walls: "))
num_exterior_walls = int(input("Enter number of Exterior walls: "))

total_cost = 0

if num_interior_walls > 0:
    interior_area = float(input("Enter surface area of each Interior wall (in sq.ft.): "))
    total_cost += num_interior_walls * interior_area * INTERIOR_COST

if num_exterior_walls > 0:
    exterior_area = float(input("Enter surface area of each Exterior wall (in sq.ft.): "))
    total_cost += num_exterior_walls * exterior_area * EXTERIOR_COST

print(f"Total painting cost: Rs.{total_cost}")


Enter number of Interior walls: 6
Enter number of Exterior walls: 4
Enter surface area of each Interior wall (in sq.ft.): 54
Enter surface area of each Exterior wall (in sq.ft.): 73
Total painting cost: Rs.9336.0
